CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "MSCards" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text NOT NULL,
    cardinfolink text NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    image text[] NOT NULL,
    CONSTRAINT "PK_MSCards" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240423211256_Initial', '9.0.0-preview.3.24172.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "MSCards" RENAME COLUMN "Longitude" TO longitude;

ALTER TABLE "MSCards" RENAME COLUMN "Latitude" TO latitude;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240423211920_init2', '9.0.0-preview.3.24172.4');

COMMIT;

